version: "3.9"
services:
  db:
    image: postgres:16
    container_name: auth_service_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_service
    ports:
      - "5432:5432"
    volumes:
      - auth_service_pg:/var/lib/postgresql/data
volumes:
  auth_service_pg:
